-- ============================================
-- Jander Imoveis - Database Schema
-- ============================================

-- Site Settings
-- Stores global configuration (WhatsApp, site name, broker name)
CREATE TABLE public.site_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  whatsapp TEXT NOT NULL DEFAULT '',
  site_name TEXT NOT NULL DEFAULT '',
  broker_name TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Public can read settings (needed for WhatsApp button on public site)
CREATE POLICY "Anyone can read settings"
  ON public.site_settings FOR SELECT
  TO anon, authenticated
  USING (true);

-- Only authenticated admin can update
CREATE POLICY "Authenticated users can update settings"
  ON public.site_settings FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Only authenticated admin can insert (initial seed)
CREATE POLICY "Authenticated users can insert settings"
  ON public.site_settings FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Seed the single settings row
INSERT INTO public.site_settings (whatsapp, site_name, broker_name)
VALUES ('', '', '');

-- ============================================
-- Keep Alive
-- Minimal table for keep-alive pings to prevent Supabase free-tier pausing
-- ============================================

CREATE TABLE public.keep_alive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pinged_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- Allow anon to read (for the cron ping)
CREATE POLICY "Anyone can read keep_alive"
  ON public.keep_alive FOR SELECT
  TO anon, authenticated
  USING (true);

-- ============================================
-- Properties
-- Real estate listings (used from Phase 2 onwards)
-- ============================================

CREATE TABLE public.properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC(12,2),
  property_type TEXT,
  bedrooms INT,
  bathrooms INT,
  area NUMERIC(10,2),
  address TEXT,
  neighborhood TEXT,
  city TEXT,
  state TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  status TEXT DEFAULT 'disponivel' CHECK (status IN ('disponivel', 'reservado', 'vendido')),
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- Anyone can read properties (public site)
CREATE POLICY "Anyone can read properties"
  ON public.properties FOR SELECT
  TO anon, authenticated
  USING (true);

-- Only authenticated admin can insert
CREATE POLICY "Authenticated users can insert properties"
  ON public.properties FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Only authenticated admin can update
CREATE POLICY "Authenticated users can update properties"
  ON public.properties FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Only authenticated admin can delete
CREATE POLICY "Authenticated users can delete properties"
  ON public.properties FOR DELETE
  TO authenticated
  USING (true);

-- ============================================
-- Property Images
-- Photos linked to properties (used from Phase 3 onwards)
-- ============================================

CREATE TABLE public.property_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id UUID REFERENCES public.properties ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  position INT DEFAULT 0,
  is_cover BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;

-- Anyone can read property images (public site)
CREATE POLICY "Anyone can read property_images"
  ON public.property_images FOR SELECT
  TO anon, authenticated
  USING (true);

-- Only authenticated admin can insert
CREATE POLICY "Authenticated users can insert property_images"
  ON public.property_images FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Only authenticated admin can update
CREATE POLICY "Authenticated users can update property_images"
  ON public.property_images FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Only authenticated admin can delete
CREATE POLICY "Authenticated users can delete property_images"
  ON public.property_images FOR DELETE
  TO authenticated
  USING (true);

-- ============================================
-- STORAGE BUCKET (create manually in Supabase Dashboard)
-- ============================================
-- Bucket name: property-images
-- Public: true (images served directly via public URL)
-- File size limit: 5MB
-- Allowed MIME types: image/jpeg, image/png, image/webp
--
-- RLS policies (apply in Supabase Dashboard -> Storage -> Policies):
-- SELECT: Allow public access (anon, authenticated)
-- INSERT: Allow authenticated only
-- UPDATE: Allow authenticated only
-- DELETE: Allow authenticated only
-- ============================================

-- Storage bucket policies (run after creating bucket in dashboard)
-- These use the storage schema, not public
CREATE POLICY "Public read access for property images"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'property-images');

CREATE POLICY "Authenticated users can upload property images"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'property-images');

CREATE POLICY "Authenticated users can update property images"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'property-images');

CREATE POLICY "Authenticated users can delete property images"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'property-images');
